In [1]:
# Import Dependencies
import pandas as pd

# Pulled Original CSV

In [2]:
# Reference the file where the CSV is located
file = "SpeedDatingData.csv"

# Import the data into a Pandas DataFrame
speed_df = pd.read_csv(file)
speed_df

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,...,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,...,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,552,22.0,1,44,2,21,22,14,10.0,5,...,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0
8374,552,22.0,1,44,2,21,22,13,10.0,4,...,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0
8375,552,22.0,1,44,2,21,22,19,10.0,10,...,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0
8376,552,22.0,1,44,2,21,22,3,10.0,16,...,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0
8377,552,NaN,1,44,2,21,22,2,10.0,15,...,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0

# New DataFrame of the columns we want to use

In [3]:
# Delete extraneous columns
reduced_speed = speed_df[['iid','gender','wave','match','samerace','age_o','race_o',
                        'pf_o_att','pf_o_sin','pf_o_int','pf_o_fun','pf_o_amb','pf_o_sha',
                        'dec_o','attr_o','sinc_o','intel_o','fun_o','amb_o','shar_o',
                        'age','field_cd','race','imprace','imprelig',
                        'goal','career_c','sports','tvsports','exercise','dining','museums',
                        'art','hiking','gaming','clubbing','reading','tv','theater','movies','concerts',
                        'music','shopping','yoga','exphappy','expnum','attr1_1','sinc1_1','intel1_1',
                        'fun1_1','amb1_1','shar1_1','attr2_1','sinc2_1','intel2_1','fun2_1','amb2_1',
                        'shar2_1','attr3_1','sinc3_1','fun3_1','intel3_1','amb3_1','dec',
                        'match_es','num_in_3','attr1_3','sinc1_3','intel1_3','fun1_3','amb1_3','shar1_3',
                        ]]
reduced_speed.head()

,iid,gender,wave,match,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,...,amb3_1,dec,match_es,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3
0,1,0,1,0,0,27.0,2.0,35.0,20.0,20.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
1,1,0,1,0,0,22.0,2.0,60.0,0.0,0.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
2,1,0,1,1,1,22.0,4.0,19.0,18.0,19.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
3,1,0,1,1,0,23.0,2.0,30.0,5.0,15.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
4,1,0,1,1,0,24.0,3.0,30.0,10.0,20.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0

# Renamed Columns

In [4]:
#Clean up Column Name
renamed_speed = reduced_speed.rename(columns={'iid':'Unique ID','gender':'Gender','wave': 'Wave',
                        'match':'Match','samerace':'Same Race','age_o':'Age of Partner','race_o':'Race of Partner',
                        'pf_o_att':'Partner Preference Attractive','pf_o_sin':'Partner Preference Sincere',
                        'pf_o_int':'Partner Preference Intelligence','pf_o_fun':'Partner Preference Fun','pf_o_amb':'Partner Preference Ambition',
                        'pf_o_sha':'Partner Preference Shared Interests','dec_o': 'Decision of Partner',
                        'attr_o':'Partner Rating Attractive','sinc_o':'Partner Rating Sincere',
                        'intel_o':'Partner Rating Intelligence','fun_o':'Partner Rating Fun','amb_o':'Partner Rating Ambition',
                        'shar_o': 'Partner Rating Shared Interests','age':'Age','field_cd':'Field of Study',
                        'race':'Race','imprace':'Same Race Importance','imprelig':'Same Religion Importance',
                        'goal':'Goal of Event','career_c':'Intended Career','sports':'Interest Sports',
                        'tvsports':'Interest Watching Sports','exercise':'Interest Exercise','dining':'Interest Dining',
                        'museums':'Interest Museums','art':'Interest Art','hiking': 'Interest Hiking','gaming':'Interest Gaming',
                        'clubbing': 'Interest Clubbing','reading':'Interest Reading','tv':'Interest TV','theater':'Interest Theater',
                        'movies':'Interest Movies','concerts':'Interest Concerts','music':'Interest Music','shopping':'Interest Shopping',
                        'yoga':'Interest Yoga','exphappy':'Expectation of Happiness With Partner','expnum':'Expected Number of Matches',
                        'attr1_1':'Your Preference Attractive','sinc1_1':'Your Preference Sincere','intel1_1':'Your Preference Intelligence',
                        'fun1_1':'Your Preference Fun','amb1_1':'Your Preference Ambition','shar1_1':'Your Preference Shared Interests',
                        'attr2_1':'Opposite-Sex Preference Attractive','sinc2_1':'Opposite-Sex Preference Sincere','intel2_1':'Opposite-Sex Preference Intelligence',
                        'fun2_1':'Opposite-Sex Preference Fun','amb2_1':'Opposite-Sex Preference Ambition',
                        'shar2_1':'Opposite-Sex Preference Shared Interests','attr3_1':'Own Rating Attractive','sinc3_1':'Own Rating Sincere',
                        'fun3_1':'Own Rating Fun','intel3_1':'Own Rating Intelligence','amb3_1':'Own Rating Ambition','dec':'Decision',
                        'match_es':'Estimation of Matches','num_in_3':'Number of Dates','attr1_3':'Your Preference Attractive Post-Date',
                        'sinc1_3':'Your Preference Sincere Post-Date','intel1_3':'Your Preference Intelligence Post-Date',
                        'fun1_3':'Your Preference Fun Post-Date','amb1_3':'Your Preference Ambition Post-Date',
                        'shar1_3':'Your Preference Shared Interests Post-Date'})
renamed_speed

,Unique ID,Gender,Wave,Match,Same Race,Age of Partner,Race of Partner,Partner Preference Attractive,Partner Preference Sincere,Partner Preference Intelligence,...,Own Rating Ambition,Decision,Estimation of Matches,Number of Dates,Your Preference Attractive Post-Date,Your Preference Sincere Post-Date,Your Preference Intelligence Post-Date,Your Preference Fun Post-Date,Your Preference Ambition Post-Date,Your Preference Shared Interests Post-Date
0,1,0,1,0,0,27.0,2.0,35.0,20.0,20.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
1,1,0,1,0,0,22.0,2.0,60.0,0.0,0.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
2,1,0,1,1,1,22.0,4.0,19.0,18.0,19.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
3,1,0,1,1,0,23.0,2.0,30.0,5.0,15.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
4,1,0,1,1,0,24.0,3.0,30.0,10.0,20.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,552,1,21,0,0,26.0,3.0,10.0,10.0,30.0,...,7.0,0,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8374,552,1,21,0,0,24.0,6.0,50.0,20.0,10.0,...,7.0,0,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8375,552,1,21,0,0,29.0,3.0,40.0,10.0,30.0,...,7.0,0,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8376,552,1,21,0,0,22.0,4.0,10.0,25.0,25.0,...,7.0,0,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8377,552,1,21,0,0,22.0,4.0,20.0,20.0,10.0,...,7.0,0,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0

# Removed waves 6-9 because the attribute rankings were recorded differently than majority of waves

In [5]:
#Clean up waves
index_wave = renamed_speed[(renamed_speed['Wave'] >= 6) & (renamed_speed['Wave']<=9)].index
renamed_speed.drop(index_wave , inplace=True)
renamed_speed

,Unique ID,Gender,Wave,Match,Same Race,Age of Partner,Race of Partner,Partner Preference Attractive,Partner Preference Sincere,Partner Preference Intelligence,...,Own Rating Ambition,Decision,Estimation of Matches,Number of Dates,Your Preference Attractive Post-Date,Your Preference Sincere Post-Date,Your Preference Intelligence Post-Date,Your Preference Fun Post-Date,Your Preference Ambition Post-Date,Your Preference Shared Interests Post-Date
0,1,0,1,0,0,27.0,2.0,35.0,20.0,20.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
1,1,0,1,0,0,22.0,2.0,60.0,0.0,0.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
2,1,0,1,1,1,22.0,4.0,19.0,18.0,19.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
3,1,0,1,1,0,23.0,2.0,30.0,5.0,15.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
4,1,0,1,1,0,24.0,3.0,30.0,10.0,20.0,...,7.0,1,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,552,1,21,0,0,26.0,3.0,10.0,10.0,30.0,...,7.0,0,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8374,552,1,21,0,0,24.0,6.0,50.0,20.0,10.0,...,7.0,0,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8375,552,1,21,0,0,29.0,3.0,40.0,10.0,30.0,...,7.0,0,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8376,552,1,21,0,0,22.0,4.0,10.0,25.0,25.0,...,7.0,0,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8377,552,1,21,0,0,22.0,4.0,20.0,20.0,10.0,...,7.0,0,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0

# Changed all encoded columns to their respective names

In [6]:
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([1],'Law')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([2],'Math')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([3],'Social Science')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([4],'Medical Science')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([5],'Engineering')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([6],'English')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([7],'History')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([8],'Business')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([9],'Education')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([10],'Biological Science')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([11],'Social Work')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([12],'Undecided')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([13],'Political Science')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([14],'Film')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([15],'Fine Arts')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([16],'Languages')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([17],'Architecture')
renamed_speed['Field of Study'] = renamed_speed['Field of Study'].replace([18],'Other')

In [7]:
renamed_speed['Gender'] = renamed_speed['Gender'].replace([0],'Female')
renamed_speed['Gender'] = renamed_speed['Gender'].replace([1],'Male')

In [8]:
renamed_speed['Match'] = renamed_speed['Match'].replace([0],'No')
renamed_speed['Match'] = renamed_speed['Match'].replace([1],'Yes')

In [9]:
renamed_speed['Same Race'] = renamed_speed['Same Race'].replace([0],'No')
renamed_speed['Same Race'] = renamed_speed['Same Race'].replace([1],'Yes')

In [10]:
renamed_speed['Race'] = renamed_speed['Race'].replace([1],'Black')
renamed_speed['Race'] = renamed_speed['Race'].replace([2],'White')
renamed_speed['Race'] = renamed_speed['Race'].replace([3],'Latino')
renamed_speed['Race'] = renamed_speed['Race'].replace([4],'Asian')
renamed_speed['Race'] = renamed_speed['Race'].replace([5],'Native American')
renamed_speed['Race'] = renamed_speed['Race'].replace([6],'Other')

In [11]:
renamed_speed['Race of Partner'] = renamed_speed['Race of Partner'].replace([1],'Black')
renamed_speed['Race of Partner'] = renamed_speed['Race of Partner'].replace([2],'White')
renamed_speed['Race of Partner'] = renamed_speed['Race of Partner'].replace([3],'Latino')
renamed_speed['Race of Partner'] = renamed_speed['Race of Partner'].replace([4],'Asian')
renamed_speed['Race of Partner'] = renamed_speed['Race of Partner'].replace([5],'Native American')
renamed_speed['Race of Partner'] = renamed_speed['Race of Partner'].replace([6],'Other')

In [12]:
renamed_speed['Goal of Event'] = renamed_speed['Goal of Event'].replace([1],'Fun Night Out')
renamed_speed['Goal of Event'] = renamed_speed['Goal of Event'].replace([2],'Meet New People')
renamed_speed['Goal of Event'] = renamed_speed['Goal of Event'].replace([3],'Get a Date')
renamed_speed['Goal of Event'] = renamed_speed['Goal of Event'].replace([4],'Serious Relationship')
renamed_speed['Goal of Event'] = renamed_speed['Goal of Event'].replace([5],'Just To Do It')
renamed_speed['Goal of Event'] = renamed_speed['Goal of Event'].replace([6],'Other')

In [13]:
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([1],'Lawyer')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([2],'Academic/Research')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([3],'Psychologist')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([4],'Doctor')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([5],'Engineer')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([6],'Creative Arts')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([7],'Business/Finance')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([8],'Real Estate')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([9],'International Affairs')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([10],'Undecided')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([11],'Social Work')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([12],'Speech Pathology')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([13],'Politics')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([14],'Athletics')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([15],'Other')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([16],'Journalism')
renamed_speed['Intended Career'] = renamed_speed['Intended Career'].replace([17],'Architecture')

In [14]:
renamed_speed['Decision'] = renamed_speed['Decision'].replace([0],'No')
renamed_speed['Decision'] = renamed_speed['Decision'].replace([1],'Yes')

In [15]:
renamed_speed

,Unique ID,Gender,Wave,Match,Same Race,Age of Partner,Race of Partner,Partner Preference Attractive,Partner Preference Sincere,Partner Preference Intelligence,...,Own Rating Ambition,Decision,Estimation of Matches,Number of Dates,Your Preference Attractive Post-Date,Your Preference Sincere Post-Date,Your Preference Intelligence Post-Date,Your Preference Fun Post-Date,Your Preference Ambition Post-Date,Your Preference Shared Interests Post-Date
0,1,Female,1,No,No,27.0,White,35.0,20.0,20.0,...,7.0,Yes,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
1,1,Female,1,No,No,22.0,White,60.0,0.0,0.0,...,7.0,Yes,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
2,1,Female,1,Yes,Yes,22.0,Asian,19.0,18.0,19.0,...,7.0,Yes,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
3,1,Female,1,Yes,No,23.0,White,30.0,5.0,15.0,...,7.0,Yes,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
4,1,Female,1,Yes,No,24.0,Latino,30.0,10.0,20.0,...,7.0,Yes,4.0,NaN,15.0,20.0,20.0,15.0,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,552,Male,21,No,No,26.0,Latino,10.0,10.0,30.0,...,7.0,No,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8374,552,Male,21,No,No,24.0,Other,50.0,20.0,10.0,...,7.0,No,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8375,552,Male,21,No,No,29.0,Latino,40.0,10.0,30.0,...,7.0,No,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8376,552,Male,21,No,No,22.0,Asian,10.0,25.0,25.0,...,7.0,No,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0
8377,552,Male,21,No,No,22.0,Asian,20.0,20.0,10.0,...,7.0,No,3.0,1.0,70.0,0.0,20.0,10.0,0.0,0.0

# Converted to CSV for running analysis

In [16]:
renamed_speed.to_csv("Output/CleanedSpeed.csv",
                  encoding="utf-8", index=False, header=True)